version: "3.4"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    volumes:
      - .elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      # Keep the memory usage of ES low locally so we don't OOM.
      ES_JAVA_OPTS: -Xmx384m
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
    ports:
      - 9200:9200
